env:
  DOCKER_COMPOSE_VERSION: 1.8.0

language: ruby

rvm:
  - 2.3.1
  - ruby-head

sudo: required 
services: 
  -  docker


before_install: 
  -  sudo apt-get update
  -  sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  -  sudo docker-compose rm -f
  -  sudo docker-compose up --build 
