--- 
  # base url of the rundeck instance. Normally this is the endpoint where you log into the gui
  rundeck_url: "http://my.rundeckinstance.com:4440/"
  #  job Ids for creating and deleting a vm 
  create_job_uuid: c7235fa9-fd80-425f-8207-c92988a01da8
  delete_job_uuid: 6f1b644f-8c67-487c-9cef-2dd3de5f2dfc
  # rundeck API token
  api_token: mysecretapitoken12lk3j12 
  # sinatra environment. Right now this doesn't do anything
  environment: development
  # port for sinatra endpoint
  sinatra_port: 42069
  # number of machines you want to have in the pool
  pool_size: 3
  # number of quarantines after which we will stop creating new machines
  quarantine_limit: 2
