--- 
  # endpoint for the rundeck instance
  # this isn't validated. make sure there is a trailing slash.
  # theres an issue open to fix this.
  rundeck_url: "http://my.fake.rundeck/"
  # rundeck api token
  api_token: CMXcCZ6EFAKEBbLuX5FAKE64e6vb5XFlFAHu1RTt
  # rundeck job creation id. We require the job to take the argument -machineName 
  # and name the box accordingly
  create_job_uuid: f0eb6497-c5a9FAKE-4a35-98f7FAKE-eb88d068c606
  # rundeck job deletion id. This also requires the -machineName argument
  delete_job_uuid: f0eb6FAKE497-c5a9-4a35FAKE-98f7-eb88d068c606
  # redis machine name. Use the default port 6379. docker-compose will 
  # alias its container as 'compose_redis'
  redis_endpoint: compose_redis 
  # sinatra config we aren't using atm
  environment: development
  # port for poolsclosed api
  sinatra_port: 42069
  # number of machines to maintain
  pool_size: 3
  # number of failures we tolerate before we stop calling the rundeck create job
  # this is intended to require manual intervention for now
  quarantine_limit: 2
