version: '2'
services:
  app:
    image: poolsclosed
    links:
      # this is in the form service:alias 
      - redis:compose_redis
    ports: 
      - "42069:42069"
  redis:
    image: poolsclosed/redis
    # thinking this isn't necessary
    # ports: 
    # - "6379:6379"
    volumes: 
     - redisvolume:/data
volumes:
  redisvolume:
    driver: local
